version: 2.1

orbs:
  ms_python: medasync/python@0.0.6

workflows:
  version: 2
  lint_and_test:
    jobs:
      - ms_python/prepare:
          name: prepare
      - ms_python/style_test:
          name: style_test
          source_root: src
          requires:
            - prepare
      - ms_python/test:
          name: test
          migrate_db: false
          test_steps:
            - ms_python/run_pytest:
                source_root: src
          requires:
            - prepare

